export const RESET_APP_STATE = 'RESET_APP_STATE';
export const GET_CHITS_REQUEST = 'GET_CHITS_REQUEST';
export const GET_CHITS_SUCCESS = 'GET_CHITS_SUCCESS';

export const GET_MY_CHITS_REQUEST = 'GET_MY_CHITS_REQUEST';
export const GET_MY_CHITS_SUCCESS = 'GET_MY_CHITS_SUCCESS';